DROP DATABASE IF EXISTS EventosBD;
CREATE DATABASE EventosBD;
USE EventosBD;

CREATE TABLE Local (
    idLocal INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Direccion VARCHAR(255) NOT NULL,
    Capacidad INT NOT NULL,
    Telefono VARCHAR(50) NOT NULL
);

CREATE TABLE Sector (
    idSector INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion VARCHAR(255),
    Capacidad INT NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    idLocal INT NOT NULL,
    FOREIGN KEY (idLocal) REFERENCES Local(idLocal) ON DELETE CASCADE
);

CREATE TABLE Evento (
    idEvento INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Fecha DATE NOT NULL,
    Lugar VARCHAR(45),
    Tipo VARCHAR(50),
    idLocal INT NOT NULL,
    FOREIGN KEY (idLocal) REFERENCES Local(idLocal) ON DELETE CASCADE
);

CREATE TABLE Cliente (
    idCliente INT AUTO_INCREMENT PRIMARY KEY,
    DNI INT NOT NULL,
    Nombre VARCHAR(60) NOT NULL,
    Apellido VARCHAR(45) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Telefono VARCHAR(50) NOT NULL
);

CREATE TABLE Orden (
    idOrden INT AUTO_INCREMENT PRIMARY KEY,
    Fecha DATE NOT NULL,
    Total DECIMAL(10,2) NOT NULL,
    Estado VARCHAR(50),
    idCliente INT NOT NULL,
    FOREIGN KEY (idCliente) REFERENCES Cliente(idCliente) ON DELETE CASCADE
);

CREATE TABLE Tarifa (
    idTarifa INT AUTO_INCREMENT PRIMARY KEY,
    Precio DECIMAL(10,2) NOT NULL,
    Tipo VARCHAR(50),
    idEvento INT NOT NULL,
    idSector INT NOT NULL,
    idFuncion INT NOT NULL,
    FOREIGN KEY (idEvento) REFERENCES Evento(idEvento) ON DELETE CASCADE,
    FOREIGN KEY (idSector) REFERENCES Sector(idSector) ON DELETE CASCADE
);

CREATE TABLE DetalleOrden (
    idDetalleOrden INT AUTO_INCREMENT PRIMARY KEY,
    Cantidad INT NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    idOrden INT NOT NULL,
    idTarifa INT NOT NULL,
    FOREIGN KEY (idOrden) REFERENCES Orden(idOrden) ON DELETE CASCADE,
    FOREIGN KEY (idTarifa) REFERENCES Tarifa(idTarifa) ON DELETE CASCADE
);

CREATE TABLE Entrada (
    idEntrada INT AUTO_INCREMENT PRIMARY KEY,
    Precio DECIMAL(10,2) NOT NULL,
    QR VARCHAR(255),
    idDetalleOrden INT NOT NULL,
    idSector INT NOT NULL,
    idTarifa INT NOT NULL,
    idFuncion INT NOT NULL,
    Anulada BOOLEAN DEFAULT FALSE,
    Usada BOOLEAN DEFAULT FALSE,
    Estado VARCHAR(50),
    Numero INT NOT NULL,
    FOREIGN KEY (idDetalleOrden) REFERENCES DetalleOrden(idDetalleOrden) ON DELETE CASCADE,
    FOREIGN KEY (idSector) REFERENCES Sector(idSector) ON DELETE CASCADE
);

CREATE TABLE Funcion (
    idFuncion INT AUTO_INCREMENT PRIMARY KEY,
    Descripcion VARCHAR(255),
    FechaHora DATETIME NOT NULL
);

CREATE TABLE Usuario (
    idUsuario INT AUTO_INCREMENT PRIMARY KEY,
    User VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE Rol (
    idRol INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE UsuarioRol (
    idUsuario INT NOT NULL,
    idRol INT NOT NULL,
    PRIMARY KEY (idUsuario, idRol),
    FOREIGN KEY (idUsuario) REFERENCES Usuario(idUsuario) ON DELETE CASCADE,
    FOREIGN KEY (idRol) REFERENCES Rol(idRol) ON DELETE CASCADE
);
