-- Active: 1700068523370@@127.0.0.1@3306@EventosBD
DROP DATABASE IF EXISTS EventosBD;
CREATE DATABASE IF NOT EXISTS EventosBD;
USE EventosBD;

CREATE TABLE Local (
    idLocal INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Direccion VARCHAR(255) NOT NULL,
    Capacidad INT NOT NULL,
    Telefono VARCHAR(50) NOT NULL
);

CREATE TABLE Sector (
    idSector INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion VARCHAR(255),
    Capacidad INT NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    idLocal INT NOT NULL,
    FOREIGN KEY (idLocal) REFERENCES Local(idLocal) ON DELETE CASCADE
);

CREATE TABLE Evento (
    idEvento INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Fecha DATE NOT NULL,
    Lugar VARCHAR(45),
    Tipo VARCHAR(50),
    idLocal INT NOT NULL,
    FOREIGN KEY (idLocal) REFERENCES Local(idLocal) ON DELETE CASCADE
);

CREATE TABLE Cliente (
    idCliente INT AUTO_INCREMENT PRIMARY KEY,
    DNI INT NOT NULL,
    Nombre VARCHAR(60) NOT NULL,
    Apellido VARCHAR(45) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Telefono VARCHAR(50) NOT NULL
);

CREATE TABLE Orden (
    idOrden INT AUTO_INCREMENT PRIMARY KEY,
    Fecha DATE NOT NULL,
    Total DECIMAL(10,2) NOT NULL,
    Estado VARCHAR(50),
    idCliente INT NOT NULL,
    FOREIGN KEY (idCliente) REFERENCES Cliente(idCliente) ON DELETE CASCADE
);

CREATE TABLE Entrada (
    idEntrada INT AUTO_INCREMENT PRIMARY KEY,
    Precio DECIMAL(10,2) NOT NULL,
    QR VARCHAR()
    Id_orden INT NOT NULL,
    Id_sector INT NOT NULL,
    FOREIGN KEY (Id_orden) REFERENCES Orden(Id_orden) ON DELETE CASCADE,
    FOREIGN KEY (Id_sector) REFERENCES Sector(Id_sector) ON DELETE CASCADE
);

CREATE TABLE Tarifa (
    Id_tarifa INT AUTO_INCREMENT PRIMARY KEY,
    Precio DECIMAL(10,2) NOT NULL,
    Tipo VARCHAR(50),
    Id_evento INT NOT NULL,
    Id_sector INT NOT NULL,
    FOREIGN KEY (Id_evento) REFERENCES Evento(Id_evento) ON DELETE CASCADE,
    FOREIGN KEY (Id_sector) REFERENCES Sector(Id_sector) ON DELETE CASCADE
);

CREATE TABLE Funcion (
    Id_funcion INT AUTO_INCREMENT PRIMARY KEY,
    Descripcion VARCHAR(255),
    FechaHora DATETIME NOT NULL
);

CREATE TABLE Usuario (
    IdUsuario INT AUTO_INCREMENT PRIMARY KEY,
    User VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE Rol (
    IdRol INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE UsuarioRol (
    IdUsuario INT NOT NULL,
    IdRol INT NOT NULL,
    PRIMARY KEY (IdUsuario, IdRol),
    FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario) ON DELETE CASCADE,
    FOREIGN KEY (IdRol) REFERENCES Rol(IdRol) ON DELETE CASCADE
);

INSERT INTO Rol (Nombre) VALUES ('Admin'), ('Cliente'), ('Empleado');
